name: Trigger Backend Deployment

on:
  workflow_run:
    workflows: ["Push-to-EC2-Instance"]
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BACKEND_PAT }}
          repository: aljonsantos/craftfolio-api
          event-type: deploy-backend
